theme: jekyll-theme-slate
title: GEARS
show_downloads: true
github:
  zip_url: https://github.com/jintonic/gears/zipball/master
  tar_url: https://github.com/jintonic/gears/tarball/master
  
plugins:
  - jekyll-mentions
